<a href="https://colab.research.google.com/github/Clemenciah/Personal-Learning/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch

In [0]:
import numpy as np
import torch
from torch import nn
from __future__ import print_function

In [3]:
# create  5 * 3 empty matrix
x = torch.empty(5,3)
x

tensor([[9.4973e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])

In [4]:
# create  5 * 3 random matrix
x = torch.randn(5,3)
x

tensor([[ 0.0412, -0.0431,  0.5416],
        [-0.2365,  0.5526,  0.7068],
        [-1.9469,  0.1066, -0.0114],
        [ 0.3205,  1.0351, -0.3913],
        [-0.2984, -0.3227, -1.9392]])

In [5]:
x = torch.zeros(5,3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
#Tensor is an imperative n-dimensional array running on GPU
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [7]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [8]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [9]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [10]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [11]:
#converting numpy arrays to torch tensors
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [12]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [13]:
np.add(a, 1, out = a)
a

array([2., 2., 2., 2., 2.])

In [14]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [15]:
# Compute matrix multiplication C = AB
d = 3000
# using numpy
A = np.random.randn(d, d).astype(np.float32)
B = np.random.randn(d, d).astype(np.float32)
c = A.dot(B)
c

array([[  44.41128  ,  -15.484935 ,  -21.038933 , ...,  -28.879026 ,
          27.498589 ,   -2.9646482],
       [   7.5640125,   10.702361 , -102.94628  , ...,    9.3279705,
         -11.396199 ,  -35.926243 ],
       [  33.629967 ,  -81.91637  ,  -77.563095 , ...,  -90.622345 ,
         -57.79128  ,   46.459557 ],
       ...,
       [  44.06266  ,   -3.8728828,   32.42855  , ...,    6.3762465,
          41.869957 ,   35.311806 ],
       [ -70.32914  ,   34.725853 ,   42.28804  , ...,  -16.355286 ,
        -134.97171  ,   97.17351  ],
       [ -34.86456  ,   73.53852  ,  -21.787199 , ...,   25.82336  ,
          46.956924 ,   10.320938 ]], dtype=float32)

In [17]:
#using torch with gpu
A= torch.rand(d,d).cuda()
B = torch.rand(d,d).cuda()
c = torch.mm(A,B)
c

tensor([[746.7884, 741.0547, 754.9748,  ..., 751.8769, 769.1043, 755.5163],
        [745.6445, 729.9719, 749.0021,  ..., 745.7773, 748.4438, 749.5287],
        [730.3515, 743.4229, 745.7306,  ..., 757.9393, 752.5419, 748.8590],
        ...,
        [746.2464, 745.4296, 746.0706,  ..., 747.2460, 751.7227, 754.0021],
        [725.6313, 720.1584, 741.6111,  ..., 737.2307, 753.4833, 735.9728],
        [734.8519, 727.7873, 733.7099,  ..., 739.3416, 752.2516, 738.4394]],
       device='cuda:0')

##### Autograd module does automatic differentiation
### Creating a neural network
start---Neural Network---torch.nn package---Autograd
|nn.module ---methods and layers. Under methods we have forward(input) ----returns output

# Training algorithm
#### inputs--Calculate loss -- Back propagation -- Update parameters
output_batch = model(train_batch) # Compute model output
loss = loss_fn(output_batch, labels_batch) #Calculate loss
optimizer.zero_grad() #Clear previous gradients
loss.backward() #Compute gradients of all variables wrt loss
optimizer.step() #Perform updates using calculated gradients
### Training procedure for a neural network
Define the neural network -- iterate over Dataset --Process the input --Compute the loss -- Propagate gradients back#so as to reduce the loss as we go along --Update the weights using SGD # weight = weight -learning_rate * gradient

In [18]:
# Defining the architecture of the network
import torch.nn.functional as F

class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        
        # 1 input imagechannel, 6 output channels, 5*5 square convolution kernel
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        # an affine operation: y = wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
        
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)),2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size = x.size()[1:] #all dimension except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)
        


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [19]:
# The learnable parameters of a model are returned by 'net.parameters'
params = list(net.parameters())
len(params), params[0].size()

(10, torch.Size([6, 1, 5, 5]))